enableTelemetry: false

nodeLinker: node-modules

packageExtensions:
  json-joy@^9:
    peerDependenciesMeta:
      quill-delta:
        optional: true
      rxjs:
        optional: true

yarnPath: .yarn/releases/yarn-3.6.3.cjs
