enableTelemetry: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.1.cjs

packageExtensions:
  json-joy@^9:
    peerDependenciesMeta:
      quill-delta:
        optional: true
      rxjs:
        optional: true
